// Generated by CoffeeScript 1.9.3
(function() {
  var Bookmark, americano;

  americano = require('americano-cozy');

  module.exports = Bookmark = americano.getModel('Bookmark', {
    'title': {
      type: String
    },
    'url': {
      type: String
    },
    'tags': {
      type: JSON
    },
    'description': {
      type: String
    },
    'created': {
      type: Date,
      "default": Date
    }
  });

  Bookmark.all = function(params, callback) {
    return Bookmark.request("byDate", params, callback);
  };

}).call(this);
