// Generated by CoffeeScript 1.7.1
var Bookmark, americano;

americano = require('americano');

module.exports = Bookmark = americano.getModel('Bookmark', {
  'title': {
    type: String
  },
  'url': {
    type: String
  },
  'tags': {
    type: JSON
  },
  'description': {
    type: String
  },
  'created': {
    type: Date,
    "default": Date
  }
});

Bookmark.all = function(params, callback) {
  return Bookmark.request("byDate", params, callback);
};

Bookmark.allTags = function(params, callback) {
  return Bookmark.request("tags", params, callback);
};
